### ISSUE TITLE
6线步进电机 改 4线

### ISSUE THREAD

**Issue by QGB** [3703781/mydocuments#1]
6 Pin step motor To 4 Pin

Is there any document about it ?

**Comment by 3703781** [comment]
是指35、42这类大一些步进电机吗，试试这个方法：
![a](https://user-images.githubusercontent.com/29368460/86342423-2a55db80-bc8a-11ea-8dc6-942ebf3eeb83.png)

**Comment by 3703781** [comment]
是35、42这类不是很大的步进电机吗，试试这个方法：
![image](https://user-images.githubusercontent.com/29368460/86342617-7143d100-bc8a-11ea-98c6-28fa12c1379d.png)
@QGB

**Comment by 3703781** [comment]
> 6 Pin step motor To 4 Pin
> 
> Is there any document about it ?

是35、42这类不是很大的步进电机吗，试试这个方法：
![b](https://user-images.githubusercontent.com/29368460/86342987-ed3e1900-bc8a-11ea-8b02-bd0cb79924c5.png)

**Comment by QGB** [comment]
为啥6线步进电机原来要这么设计，是6线控制更加精准吗  ？  @3703781

**Comment by QGB** [comment]
`6线步进电机
6线步进电机的结构类似于4线，在每相的任一端之间增加了一个共用抽头，如图2所示。带有这些中心抽头的步进电机通常被称为单极电机。这种接线方式最适合在较低速度下输出高扭矩的应用场景。大多数NI的步进电机接口不支持6线步进电机，但有些电机不需要使用中心抽头，可以作为4线电机正常连接。`

**Comment by QGB** [comment]
```
2．配置通用步进电机极性的方法
这一小节讲述配置通用步进电机极性的三种方式：单极性、双极性串联和双极性并联。
图 10 所示的配置模拟了一个 6 绕组的单极性步进电机。
图 11 所示的双极性配置可以以较低的工作频率传递较高的力矩。它的工作频率无法较
高，是因为串联绕组具有高的磁阻，因此电流无法快速达到峰值。
图 12 所示的双极性并联配置步进电机的输出力矩小于双极性串联配置，但是它具有更
高的工作频率，因为并联绕组配置具有低磁阻，电流可以快速达到峰值。
七、有关步进电机极性配置的结束语
至今为止，读者可能已看到了 6 线单极性步进电机和串联配置的通用步进电机之间的令
人惊异的相同点。事实上，可以通过忽略两条公共绕组的连接，将一个 6 线单极性步进电机
用作双极性步进电机。作者已经测试过，并且工作状态良好。
```

**Comment by 3703781** [comment]
> 为啥6线步进电机原来要这么设计，是6线控制更加精准吗 ？ @3703781
2相6线比2相4线更适合高速 精度方面不清楚

**Comment by QGB** [comment]
@3703781 

```
二相六线的混合式步进电机，如果有合适匹配的六线驱动器，它能在快速响应和大力矩之间灵活的切换，如果是普通的二相四线的驱动器，可以有二种接法：

1.如果需要大力矩，就接两端的抽头：

红线：A+ ，黄线：A-。（黑线是中间抽头，悬空不接）

青线：B+ ，白线：B-。（蓝线是中间抽头，悬空不接）

2，如果需要高速运转，就接中间抽头：

红线：A+，黑线：A-。（黄线不接）

青线：B+，蓝线：B-。（白线不接）
```

**Comment by QGB** [comment]
![image](https://user-images.githubusercontent.com/8005654/88395705-0fdbd180-cdf4-11ea-9776-2e2559b21b03.png)
![image](https://user-images.githubusercontent.com/8005654/88395741-1d915700-cdf4-11ea-8e83-c49ef13c7a15.png)

**Comment by 3703781** [comment]
收藏了 谢谢
